### ISSUE TITLE
default limit of 2048 channels

### ISSUE THREAD

**Issue by hardison-d** [omniti-labs/pg_amqp#23]
RabbitMQ set a new default limit of 2048 channels.
https://github.com/rabbitmq/rabbitmq-server/issues/1593
Please change default limit to 2048

**Comment by aleksey-chernenko** [comment]
You can get round it
Just edit src/librabbitmq/amqp_socket.c

diff src/librabbitmq/amqp_socket.c src/librabbitmq/amqp_socket.c.orig 
389c389
<   if (server_channel_max != 0 && (server_channel_max < channel_max || channel_max == 0)) {
---
>   if (server_channel_max != 0 && server_channel_max < channel_max) {

**Comment by xzilla** [comment]
I believe this has been addressed in PR #26
