### ISSUE TITLE
before 8.3.0 arguments macros are different

### ISSUE THREAD

**Issue by scr34m** [omniti-labs/pg_amqp#6]
Before 8.3.0 had to use `VARDATA` and `VARSIZE` instead `VARDATA_ANY` and `VARSIZE_ANY`, tested and using with 8.1.9.  Makefile changes for checking installed PG version will be usefull to make this automatic.

https://github.com/Scr34m/pg_amqp/commit/8d8b24786bae0fd7f806a0218e73ccb990cd0f21

**Comment by keithf4** [comment]
Postgres 8.1 and 8.3 are both EOL and unsupported so it is highly recommended that you upgrade to avoid serious bugs and security issues.
