### ISSUE TITLE
mac os and psql 9.2

### ISSUE THREAD

**Issue by eddwardo** [omniti-labs/pg_amqp#8]
Im experiencing some problem with running pg_amqp on Postgresql.app on MacOS 10.8.

Readme states that i can use 9.1+ version but:

```bash
(master)edd@edd-mac:~/workspace/pg_amqp$ env PG_CONFIG=/Applications/Postgres.app/Contents/MacOS/bin/pg_config make && sudo make install
edd@edd-mac:~/workspace/psql_var$ FATAL:  incompatible library "/users/edd/workspace/pg_amqp/pg_amqp.so": version mismatch
DETAIL:  Server is version 9.2, library is version 9.1.
```

Is it possible to make more clear how to build extension for 9.2 version?

**Comment by keithf4** [comment]
Very late reply here, but this seems like more of an issue with the way you have Postgres and its associated libraries installed on your system. If this is still an problem you're having after the next release I push out, please reopen this issue, or try sending this issue to the mailing lists.
